[package]
name = "stackchan-rs"
version = "0.1.0"
edition = "2024"
authors = ["Kenta Ida <fuga@fugafuga.org>"]
repository = "https://github.com/ciniml/m5stack-avatar-rs"
license = "MIT OR Apache-2.0"
description = "Rust implementation of Stackchan (ｽﾀｯｸﾁｬﾝ) firmware"

[dependencies]
micromath = "2.0"
