[package]
name = "stackchan-m5stack"
version = "0.1.0"
edition = "2024"
authors = ["Kenta Ida <fuga@fugafuga.org>"]
repository = "https://github.com/ciniml/m5stack-avatar-rs"
license = "MIT OR Apache-2.0"
description = "Rust implementation of Stackchan (ｽﾀｯｸﾁｬﾝ) firmware for M5Stack Core2"

[dependencies]
embedded-graphics = "0.8"
embedded-hal = "1.0"
embedded-hal-bus = "0.3"
num_enum = { version = "0.7", default-features = false }
variant_count = { version = "1.1.0", default-features = false }

stackchan-rs = { path = "../.." }
m5stack-avatar-rs = { path = "../../m5stack-avatar-rs" }
m5drivers-rs = { path = "../../m5drivers-rs" }

esp-hal = { version = "1.1", features = ["esp32", "unstable"] }
esp-backtrace = { version = "0.19", features = ["esp32", "panic-handler", "println"] }
esp-println = { version = "0.17", features = ["esp32", "log-04"] }
esp-alloc = "0.10"

micromath = "2.0"
critical-section = "1"
heapless = "0.8"

[profile.release]
debug = true
lto = "off"
opt-level = 3

[profile.dev]
lto = "off"
